name: 'Verify WASI ABI files are up-to-date'
description: 'Verify WASI ABI files are up-to-date'
inputs:
  wai-abi-tag:
    description: 'version of the `wai-abi` tool to use'
    required: true
    default: '0.1.0'
runs:
  using: 'node12'
  main: 'main.js'
